---
title: "CRONOGRAMA TE2025-MICROBIOMA"
---

| **Módulo**                                                                     | **Tópico**                                               | **Conteúdo**                                                                                                                                                                                                                                                                                                                                                                      |
|--------------------------------------------------------------------------------|----------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Módulo 1: Introdução à Análise de Microbioma**                               | Conceitos de Microbioma, Metagenômica e Metataxonômica   | Definição de microbioma e o papel das análises ômicas para desvendar a diversidade microbiana em diferentes ambientes.                                                                                                                                                                                                                                                            |
|                                                                                | Aplicações do estudo de microbiomas                      | Exemplos de estudos na área de ciências agrárias.                                                                                                                                                                                                                                                                                                                                 |
| **Módulo 2: Introdução ao Ambiente de Computação**                             | Linux para Bioinformática                                | Comandos básicos do Linux, navegação pelo sistema de arquivos, manipulação de arquivos e scripts, e princípios de automação de tarefas com scripts shell.                                                                                                                                                                                                                         |
|                                                                                | Instalação, Gerenciamento de Softwares e bancos de dados | Ferramentas essenciais para análises de dados.                                                                                                                                                                                                                                                                                                                                    |
| **Módulo 3: Introdução ao R para Análises de Dados**                           | Fundamentos do R e RStudio                               | Estrutura de dados, tipos de operadores e funções.                                                                                                                                                                                                                                                                                                                                |
|                                                                                | Relatórios Reprodutíveis                                 | Geração de documentos automatizados utilizando Quarto para garantir a reprodutibilidade das análises.                                                                                                                                                                                                                                                                             |
|                                                                                | Manipulação de dados e visualização gráfica              | Introdução a pacotes relacionados à análise de microbiomas.                                                                                                                                                                                                                                                                                                                       |
| **Módulo 4: Controle de Qualidade de Leituras NGS**                            | Introdução ao Sequenciamento de Nova Geração (NGS)       | Fundamentos dos principais métodos de sequenciamento e suas aplicações em estudos metagenômicos/metataxonômicos.                                                                                                                                                                                                                                                                  |
|                                                                                | Pré-processamento de sequências                          | \- Controle de Qualidade com FastQC e MultiQC<br>- Remoção de adaptadores e sequências de baixa qualidade<br>- Fusão de sequências.                                                                                                                                                                                                                                               |
| **Módulo 5: Chamada de Variantes (pipeline DADA2) e Classificação Taxonômica** | Pipeline DADA2                                           | \- Controle de qualidade<br>- Correção de erros<br>- Estimativa de ASVs<br>- Classificação Taxonômica.                                                                                                                                                                                                                                                                            |
|                                                                                | Bancos de dados                                          | Silva, RDP, RefRDP, GTDB.                                                                                                                                                                                                                                                                                                                                                         |
| **Módulo 6: Análise Ecológica e Funcional**                                    | Curvas de rarefação                                      | Curvas de rarefação.                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                | Composição taxonômica                                    | Composição taxonômica.                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                | Índice de diversidade                                    | \- Métricas de diversidade (descritores da diversidade dentro de uma comunidade): índices de Riqueza, Shannon, Simpson, PD, entre outros. Comparações entre grupos.<br>- Diversidade β (comparação da diversidade entre diferentes comunidades medindo sua distância). Comparações entre grupos e visualizações como gráficos de ordenação (Supervisionado e não-supervisionado). |
|                                                                                | Abundância diferencial                                   | Abundância diferencial.                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                | Microbioma Core                                          | Microbioma Core.                                                                                                                                                                                                                                                                                                                                                                  |
